server:
  port: 8001

spring:
  application:
    name: cloud-payment-com.choi.springcloud.service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.43.41.69:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 6680124


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.choi.springcloud.entities


eureka:
  client:
    #表示是否将自己注册进eurekaserver 默认为true
    register-with-eureka: true
    #是否从eurekaserver抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true，才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
      instance-id: payment8001
      prefer-ip-address: true
      #eureka客户端向服务器发送心跳的时间间隔，单位为秒，默认30秒
#      lease-renewal-interval-in-seconds: 1
#      #eureka服务器在收到最后一次心跳后等待的时间上限，单位为秒，超过则剔除服务
#      lease-expiration-duration-in-seconds: 2